# Code generated by ios-app-manager. Edit only the custom section below.

APP_NAME := ReluxRouterSample
BUNDLE_ID := com.reluxworks.reluxroutersample
TEAM_ID := 262RZ595FP
MODULES_PATH := Packages
SCHEME ?= ReluxRouterSample
DESTINATION ?= platform=iOS Simulator,name=iPhone 16,OS=17.0
BUILD_DESTINATION ?= generic/platform=iOS Simulator
TEST_DESTINATION ?= $(DESTINATION)
WORKSPACE ?= $(APP_NAME).xcworkspace
DERIVED_DATA_PATH ?= $(CURDIR)/DerivedData
TUIST_GENERATE_FLAGS ?= --no-open
PACKAGE_ARTIFACT_CLEANUP_CMD ?= :

.DEFAULT_GOAL := help
.PHONY: setup resetup generate run-pre-tuist-generate-scripts build test clean-package-artifacts clean deep-clean lint format validate install-tools periphery help

setup: ## Install Tuist dependencies and generate project files
	@tuist install
	@$(MAKE) run-pre-tuist-generate-scripts
	@tuist generate $(TUIST_GENERATE_FLAGS)

resetup: ## Clean and run setup again
	@$(MAKE) clean
	@$(MAKE) setup

generate: ## Generate the Xcode project with Tuist
	@tuist generate $(TUIST_GENERATE_FLAGS)

run-pre-tuist-generate-scripts: ## Run configured scripts before Tuist project generation
	@:

build: ## Build the app with xcodebuild
	@set -e; \
	trap '$(MAKE) clean-package-artifacts >/dev/null' EXIT; \
	tuist generate $(TUIST_GENERATE_FLAGS); \
	xcodebuild -workspace "$(WORKSPACE)" -scheme "$(SCHEME)" -destination "$(BUILD_DESTINATION)" -derivedDataPath "$(DERIVED_DATA_PATH)" build

test: ## Run tests with xcodebuild
	@set -e; \
	trap '$(MAKE) clean-package-artifacts >/dev/null' EXIT; \
	tuist generate $(TUIST_GENERATE_FLAGS); \
	xcodebuild -workspace "$(WORKSPACE)" -scheme "$(SCHEME)" -destination "$(TEST_DESTINATION)" -derivedDataPath "$(DERIVED_DATA_PATH)" test

clean-package-artifacts: ## Clean generated artifacts left inside local package checkouts
	@$(PACKAGE_ARTIFACT_CLEANUP_CMD)

clean: ## Clean Tuist artifacts and local DerivedData
	@tuist clean
	@rm -rf "$(DERIVED_DATA_PATH)"

deep-clean: ## Remove Xcode and SwiftPM caches for a full reset
	@rm -rf "$(DERIVED_DATA_PATH)"
	@rm -rf ~/Library/Developer/Xcode/DerivedData
	@rm -rf ~/Library/Caches/org.swift.swiftpm
	@rm -rf ~/Library/org.swift.swiftpm
	@rm -rf ~/.swiftpm
	@rm -rf ~/Library/Caches/com.apple.dt.Xcode

lint: ## Run SwiftLint
	@swiftlint

format: ## Format Swift files with SwiftFormat
	@swiftformat .

validate: lint build ## Run lint checks and build

install-tools: ## Install local tooling with Homebrew
	@brew install tuist swiftlint swiftformat periphery jq

periphery: ## Run dead-code analysis with Periphery
	@periphery scan --workspace "$(WORKSPACE)" --schemes "$(SCHEME)"

help: ## Show available Make targets
	@awk 'BEGIN {FS = ":.*##"; printf "\nAvailable targets:\n"} /^[a-zA-Z0-9_.-]+:.*##/ {printf "  %-20s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# --- Generated targets above --- #

# --- Custom targets below --- #
# Add custom targets and variables below. This section is preserved on regeneration.
